### PR TITLE
Rails 5 compatibility

### PR DESCRIPTION
**Pull request by kekin-gada**

### CODE REVIEW

**Comment by kekin-gada** [comment]
@abhishekjain16 _a Please review.

**Comment by vipulnsward** [comment]
This does not need to go to master. You can continue keeping this branch and using it on BigBinary website. We might probably need to make it public so that it can be used in Gemfile there.

**Comment by kekin-gada** [comment]
@vipulnsward: This repository is already public, if that is what you meant. I will use this branch on bigbinary website for now.

**Comment by abhishekjain16** [comment]
@kekin-gada Yes. We do not need this to be merged to master.
This branch would be used on BigBinary website until https://github.com/rails/actionpack-page_caching/pull/32 is merged.
We can close this PR.

**Pull request closed without merging**
